[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[log]
# // DebugLevel: "debug",
# // InfoLevel:  "info",
# // WarnLevel:  "warning",
# // ErrorLevel: "error",
# // FatalLevel: "fatal",
# // PanicLevel: "panic",
level = "debug"
format = "text"
to = "stdout"